/**
 * tray.js
 *
 * System tray menu driven by assets/state-manifest.json (generated by
 * scripts/gen_state_manifest.mjs from src/renderer/state-catalog.mjs).
 *
 * Shows only states that have art delivered and that have menuGroup assigned
 * (catalog excludes system-only states like LAND by setting menuGroup: null).
 *
 * IMPORTANT: do NOT call any paths.js getter at module top level — they read
 * app.isPackaged, which is only safe to access after app.whenReady().  We
 * defer manifest reading to createTray().
 */
const { Tray, Menu, nativeImage, app } = require('electron');
const { getIconPath, getStateManifestPath } = require('./paths');
const { toggleWindow } = require('./window');
const fs = require('fs');

let manifestCache = null;
function loadManifest() {
    if (manifestCache !== null) return manifestCache;
    try {
        const p = getStateManifestPath();
        if (p && fs.existsSync(p)) {
            manifestCache = JSON.parse(fs.readFileSync(p, 'utf8'));
            return manifestCache;
        }
        manifestCache = false;
    } catch (e) {
        console.warn('[tray] failed to load state-manifest.json:', e.message);
        manifestCache = false;
    }
    return manifestCache;
}

function refreshManifest() {
    manifestCache = null;
    return loadManifest();
}

/** Re-derive the (group, [items]) list from the manifest. */
function deriveTrayGroups() {
    if (!manifestCache || !Array.isArray(manifestCache.states) || !manifestCache.states.length) {
        return { groups: [], showUnfinished: false };
    }
    const order = [];
    const map = new Map();
    for (const s of manifestCache.states) {
        const g = s.menuGroup;
        const hasSprite = !!s.hasSprite;
        if (!g) continue;
        if (!hasSprite) continue;       // tray menu by default hides missing-art states
        if (!map.has(g)) { map.set(g, []); order.push(g); }
        // label and key aren't in manifest (renderer-only strings); re-import a copy.
        // We piggy-back the catalog here so we need the same string values.
        // The renderer maintains STATE_CATALOG; here we only need menu keys
        // resolved elsewhere — see rendererMenusFromCatalog in main.js startup.
        map.get(g).push(s);
    }
    return { groups: order.map(label => ({ label, items: map.get(label) })) };
}

/** Readable labels/keys for tray strings are baked into the JS catalog.
 *  We embed a small mirror here so the tray can build menu items without
 *  reading renderer source. Keep this in sync via the same SSOT contract.
 */
const TRAY_LABEL_KEY = {
    idle:     { label: '待机', key: '1' },
    walk:     { label: '行走', key: '2' },
    sit:      { label: '坐下', key: '3' },
    eat:      { label: '吃饭', key: '4' },
    think:    { label: '思考', key: '5' },
    cheer:    { label: '干杯', key: '6' },
    surprise: { label: '惊喜', key: '7' },
    sleep:    { label: '睡觉', key: '8' },
    yawn:     { label: '哈欠', key: '9' },
    love:     { label: '比心', key: '0' },
    work:     { label: '工作', key: 'W' },
    peek:     { label: '偷看', key: 'P' },
    wave:     { label: '挥手', key: 'V' },
    drink:    { label: '举杯', key: 'B' },
    run:      { label: '小跑', key: 'R' },
    stretch:  { label: '伸懒腰', key: 'S' },
    angry:    { label: '生气', key: 'X' },
};

function labelFor(stateId) {
    return TRAY_LABEL_KEY[stateId]?.label ?? stateId;
}
function keyFor(stateId) {
    return TRAY_LABEL_KEY[stateId]?.key ?? '';
}

let trayInstance = null;

function buildMenu(sendState, withShowUnfinished = false) {
    const { groups } = deriveTrayGroups();

    const items = [
        { label: 'Date Night Girl', enabled: false },
        { type: 'separator' },
    ];

    groups.forEach((g, i) => {
        if (i > 0) items.push({ type: 'separator' });
        for (const s of g.items) {
            const id  = s.key;                  // catalog key === lowercase sprite id
            const lbl = labelFor(id);
            const k   = keyFor(id);
            items.push({
                label: `${lbl}  (${k})`,
                click: () => sendState(id),
            });
        }
    });

    items.push(
        { type: 'separator' },
        { label: '开始番茄钟',  click: () => sendState('__cmd:pomodoro:start') },
        { label: '今日待办',    click: () => sendState('__cmd:room:open:todos') },
        { label: '角色状态',    click: () => sendState('__cmd:room:open:stats') },
        {
            label: '快捷场景',
            submenu: [
                { label: '自由陪伴', click: () => sendState('__cmd:scene:manual') },
                { label: '专注工作', click: () => sendState('__cmd:scene:focus') },
                { label: '轻松陪伴', click: () => sendState('__cmd:scene:relaxed') },
                { label: '深夜休息', click: () => sendState('__cmd:scene:night') },
                { type: 'separator' },
                { label: '打开场景设置', click: () => sendState('__cmd:room:open:settings') },
            ],
        },
        { type: 'separator' },
        { label: '勿扰模式 (DND)', click: () => sendState('__cmd:dnd:toggle') },
        { type: 'separator' },
        { label: '显示 / 隐藏',  click: () => toggleWindow() },
        { type: 'separator' },
        { label: '退出', click: () => {
            global.appIsQuitting = true;
            app.quit();
        } },
    );

    return Menu.buildFromTemplate(items);
}

function createTray(sendState) {
    loadManifest();   // safe to call now (app.whenReady has fired)
    const iconPath = getIconPath();
    let image;
    try {
        image = nativeImage.createFromPath(iconPath);
        if (image.isEmpty()) throw new Error('empty');
    } catch (e) {
        image = nativeImage.createEmpty();
    }
    trayInstance = new Tray(image);
    trayInstance.setToolTip('Date Night Girl - 桌面陪伴伙伴');
    trayInstance.setContextMenu(buildMenu(sendState));
    trayInstance.on('click', () => toggleWindow());
    return trayInstance;
}

function updateTrayMenu(sendState) {
    if (trayInstance && !trayInstance.isDestroyed()) {
        refreshManifest();
        trayInstance.setContextMenu(buildMenu(sendState));
    }
}

module.exports = { createTray, updateTrayMenu, refreshManifest };
